version: "3.8"
services:
    app:
        image: fastapi-app
        build:
            context: .
            dockerfile: Dockerfile.app
        volumes:
            - ./www:/app/www

    nginx:
        image: nginx-proxy
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports: 
            - 8081:80