version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        volumes:
            - ./www:/app/www

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports: 
            - 8081:80