services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        environment:
            my-env-variable: "hello from the compose file!"
        volumes:
            - ./www:/app/www
    nginx:
        image: nginx:latest
        ports:
            - 8081:80
        configs:
            - source: nginx_conf
              target: /etc/nginx/nginx.conf
        depends_on:
            - app

configs:
    nginx_conf:
        file: nginx.conf