services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        environment:
            my-env-variable: "hello from the compose file!"
        volumes:
            - ./www:/app/www

    nginx:
        image: nginx:latest
        ports:
            - 8081:80
            - 4431:443
        configs:
            - source: nginx_conf
              target: /etc/nginx/nginx.conf       
        secrets:
           - source: cert
             target: /etc/ssl/private/cert.pem
           - source: key
             target: /etc/ssl/private/key.pem
        depends_on:
            - app

secrets:
    cert:
        file: cert.pem
    key:
        file: key.pem

configs:
    nginx_conf:
        file: nginx.conf